export const PLACES = {
  // ── England ───────────────────────────────────────────────
  lincolnshire:   { lat: 53.23, lng: -0.54,  label: "Lincolnshire, England" },
  wales:          { lat: 52.13, lng: -3.78,  label: "Wales" },
  scrooby:        { lat: 53.42, lng: -1.01,  label: "Scrooby, Nottinghamshire" },
  frampton_gl:    { lat: 51.77, lng: -2.40,  label: "Frampton, Gloucestershire" },
  suffolk_eng:    { lat: 52.19, lng: 1.00,   label: "Suffolk, England" },

  // ── Massachusetts ─────────────────────────────────────────
  boston:         { lat: 42.36, lng: -71.06, label: "Boston, MA" },
  duxbury_ma:     { lat: 41.99, lng: -70.67, label: "Duxbury, MA" },
  worcester_ma:   { lat: 42.26, lng: -71.80, label: "Worcester, MA" },
  wenham:         { lat: 42.60, lng: -70.88, label: "Wenham, MA" },
  ipswich:        { lat: 42.68, lng: -70.84, label: "Ipswich, MA" },
  beverly_ma:     { lat: 42.56, lng: -70.88, label: "Beverly, MA" },
  plymouth:       { lat: 41.96, lng: -70.67, label: "Plymouth, MA" },
  quaboag:        { lat: 42.20, lng: -72.09, label: "Quaboag, MA" },
  salisbury:      { lat: 42.53, lng: -70.86, label: "Salisbury, MA" },
  manchester_ma:  { lat: 42.58, lng: -70.77, label: "Manchester, MA" },
  brookfield:     { lat: 42.21, lng: -72.09, label: "Brookfield, MA" },
  ma:             { lat: 42.36, lng: -71.06, label: "Massachusetts" },
  bristol_ma:     { lat: 41.90, lng: -71.10, label: "Bristol County, MA" },

  // ── Rhode Island ──────────────────────────────────────────
  providence:     { lat: 41.82, lng: -71.41, label: "Providence, RI" },
  bristol_ri:     { lat: 41.68, lng: -71.27, label: "Bristol, RI" },
  barrington_ri:  { lat: 41.74, lng: -71.32, label: "Barrington, RI" },
  newport_ri:     { lat: 41.49, lng: -71.31, label: "Newport, RI" },

  // ── Connecticut ───────────────────────────────────────────
  norwich_ct:     { lat: 41.52, lng: -72.08, label: "Norwich, CT" },
  new_london_ct:  { lat: 41.36, lng: -72.10, label: "New London, CT" },
  hartford_ct:    { lat: 41.76, lng: -72.69, label: "Hartford, CT" },
  griswold_ct:    { lat: 41.58, lng: -71.93, label: "Griswold, CT" },
  preston_ct:     { lat: 41.51, lng: -71.96, label: "Preston, CT" },
  stonington_ct:  { lat: 41.34, lng: -71.91, label: "Stonington, CT" },
  stafford_ct:    { lat: 41.98, lng: -72.28, label: "Stafford, CT" },
  norfolk_ct:     { lat: 41.99, lng: -73.22, label: "Norfolk, CT" },
  litchfield_ct:  { lat: 41.75, lng: -73.18, label: "Litchfield, CT" },
  torrington_ct:  { lat: 41.80, lng: -73.12, label: "Torrington, CT" },

  // ── New York ──────────────────────────────────────────────
  chenango_ny:    { lat: 42.49, lng: -75.60, label: "Chenango County, NY" },
  new_hudson_ny:  { lat: 42.22, lng: -78.10, label: "New Hudson, NY" },
  genoa_ny:       { lat: 42.67, lng: -76.54, label: "Genoa, NY" },
  locke_ny:       { lat: 42.67, lng: -76.42, label: "Locke, NY" },
  ny:             { lat: 42.65, lng: -74.00, label: "New York" },

  // ── Vermont / Maine ───────────────────────────────────────
  arlington_vt:   { lat: 43.08, lng: -73.15, label: "Arlington, VT" },
  maine:          { lat: 44.69, lng: -69.38, label: "Maine" },
  middletown_vt:  { lat: 43.52, lng: -72.97, label: "Middletown, VT" },
  bennington_vt:  { lat: 42.88, lng: -73.20, label: "Bennington, VT" },

  // ── Maryland ──────────────────────────────────────────────
  somerset_md:    { lat: 38.09, lng: -75.84, label: "Somerset County, MD" },
  frederick_md:   { lat: 39.41, lng: -77.41, label: "Frederick, MD" },
  washington_md:  { lat: 39.62, lng: -77.72, label: "Washington County, MD" },
  montgomery_md:  { lat: 39.14, lng: -77.20, label: "Montgomery County, MD" },
  maryland:       { lat: 39.05, lng: -76.64, label: "Maryland" },

  // ── Virginia ──────────────────────────────────────────────
  amherst_va:     { lat: 37.58, lng: -79.05, label: "Amherst, VA" },
  appomattox_va:  { lat: 37.36, lng: -78.82, label: "Appomattox, VA" },
  virginia:       { lat: 37.43, lng: -78.66, label: "Virginia" },

  // ── Kentucky ──────────────────────────────────────────────
  hardin_ky:      { lat: 37.63, lng: -85.96, label: "Hardin County, KY" },
  garrard_ky:     { lat: 37.64, lng: -84.56, label: "Garrard County, KY" },
  nelson_ky:      { lat: 37.80, lng: -85.52, label: "Nelson County, KY" },
  madison_ky:     { lat: 37.73, lng: -84.30, label: "Madison County, KY" },
  paint_lick_ky:  { lat: 37.57, lng: -84.43, label: "Paint Lick, KY" },
  new_haven_ky:   { lat: 37.54, lng: -85.59, label: "New Haven, KY" },
  larue_ky:       { lat: 37.56, lng: -85.72, label: "LaRue County, KY" },
  kentucky:       { lat: 37.84, lng: -84.27, label: "Kentucky" },

  // ── Indiana ───────────────────────────────────────────────
  vevay_in:       { lat: 38.74, lng: -85.07, label: "Vevay, IN" },
  switzerland_in: { lat: 38.86, lng: -85.07, label: "Switzerland County, IN" },
  washington_in:  { lat: 38.61, lng: -86.12, label: "Washington County, IN" },
  harrison_in:    { lat: 38.18, lng: -86.10, label: "Harrison County, IN" },
  parke_in:       { lat: 39.78, lng: -87.19, label: "Parke County, IN" },
  rome_city_in:   { lat: 41.49, lng: -85.37, label: "Rome City, IN" },
  greene_park_in: { lat: 39.01, lng: -87.00, label: "Greene County, IN" },
  indiana:        { lat: 40.27, lng: -86.13, label: "Indiana" },

  // ── Pennsylvania ─────────────────────────────────────────
  franklin_pa:    { lat: 41.38, lng: -77.72, label: "Franklin County, PA" },

  // ── Illinois ──────────────────────────────────────────────
  macoupin_il:    { lat: 39.26, lng: -89.92, label: "Macoupin County, IL" },
  illinois:       { lat: 40.00, lng: -89.00, label: "Illinois" },
  lawrence_il:    { lat: 38.72, lng: -87.73, label: "Lawrence County, IL" },
  clay_co_il:     { lat: 38.76, lng: -88.50, label: "Clay County, IL" },
  cumberland_il:  { lat: 39.27, lng: -88.24, label: "Cumberland County, IL" },
  mattoon_il:     { lat: 39.48, lng: -88.37, label: "Mattoon, IL" },
  quincy_il:      { lat: 39.94, lng: -91.41, label: "Quincy, IL" },
  taylorville_il: { lat: 39.55, lng: -89.29, label: "Taylorville, IL" },
  hillsboro_il:   { lat: 39.15, lng: -89.49, label: "Hillsboro, IL" },
  effingham_il:   { lat: 39.12, lng: -88.54, label: "Effingham, IL" },
  coles_il:       { lat: 39.52, lng: -88.21, label: "Coles County, IL" },
  shelby_co_il:   { lat: 39.40, lng: -88.79, label: "Shelby County, IL" },
  sangamon_il:    { lat: 39.78, lng: -89.65, label: "Sangamon County, IL" },
  east_peoria_il: { lat: 40.67, lng: -89.54, label: "East Peoria, IL" },
  mt_zion_il:     { lat: 39.77, lng: -88.87, label: "Mt. Zion, IL" },
  kincaid_il:     { lat: 39.59, lng: -89.41, label: "Kincaid, IL" },
  neoga_il:       { lat: 39.32, lng: -88.45, label: "Neoga, IL" },
  decatur_il:     { lat: 39.84, lng: -88.95, label: "Decatur, IL" },
  macon_il:       { lat: 39.71, lng: -88.99, label: "Macon, IL" },
  moultrie_il:    { lat: 39.60, lng: -88.62, label: "Moultrie County, IL" },

  // ── Ohio ──────────────────────────────────────────────────
  moss_run_oh:    { lat: 39.65, lng: -81.47, label: "Moss Run, OH" },

  // ── Idaho ─────────────────────────────────────────────────
  lewiston_id:    { lat: 46.42, lng: -117.02, label: "Lewiston, ID" },
  winchester_id:  { lat: 46.24, lng: -116.63, label: "Winchester, ID" },
  clarkston_wa:   { lat: 46.42, lng: -117.04, label: "Clarkston, WA" },

  // ── Michigan ──────────────────────────────────────────────
  sullivan_mi:    { lat: 43.92, lng: -86.00, label: "Sullivan, MI" },
  howard_mi:      { lat: 43.40, lng: -85.47, label: "Howard City, MI" },
  prairie_mi:     { lat: 43.62, lng: -85.14, label: "Prairie, MI" },

  // ── Missouri ──────────────────────────────────────────────
  howard_mo:      { lat: 39.14, lng: -92.67, label: "Howard County, MO" },

  // ── Wisconsin / Iowa / Kansas ─────────────────────────────
  madison_wi:     { lat: 43.07, lng: -89.40, label: "Madison, WI" },
  waverly_ia:     { lat: 42.73, lng: -92.47, label: "Waverly, IA" },
  wassenville_ia: { lat: 42.00, lng: -93.00, label: "Iowa" },
  kansas:         { lat: 38.67, lng: -98.49, label: "Kansas" },
  ellis_ks:       { lat: 38.94, lng: -99.57, label: "Ellis County, KS" },

  // ── Netherlands ───────────────────────────────────────────
  rotterdam:      { lat: 51.92, lng: 4.48,   label: "Rotterdam, Netherlands" },

  // ── New Jersey ────────────────────────────────────────────
  elizabeth_nj:   { lat: 40.66, lng: -74.21, label: "Elizabeth, NJ" },

  // ── England (additional) ──────────────────────────────────
  burton_cottles: { lat: 51.43, lng: -1.93,  label: "Burton Cottles, Lincolnshire, England" },
}

export const people = [
  // ── Generation 1 ──────────────────────────────────────────
  {
    id: "richard-coy-1590",
    name: "Richard Coy",
    birth: { year: 1590, place: "lincolnshire" },
    death: { year: 1638, place: "lincolnshire" },
    isMainLine: true,
    tags: [],
    generation: 1,
    spouseId: "lucy-ann-lenten",
    notes: "Patriarch of the American Coy line. Born and died in Lincolnshire, England.",
  },
  {
    id: "lucy-ann-lenten",
    name: "Lucy Ann Lenten",
    birth: { year: 1601, place: "burton_cottles" },
    death: { year: 1679, place: "lincolnshire" },
    isMainLine: false,
    tags: [],
    generation: 1,
    spouseId: "richard-coy-1590",
    notes: "Wife of the patriarch Richard Coy. Confirmed by the Barton family genealogy (one-barton-family.us, b3236.html). Remained in Lincolnshire; their sons Matthew and Richard emigrated to Massachusetts in 1638 after Richard Coy's death.",
  },

  // ── Generation 2 ──────────────────────────────────────────
  {
    id: "matthew-coy-i",
    name: "Matthew Coy I",
    birth: { year: 1623, place: "lincolnshire" },
    death: { year: 1677, place: "wenham" },
    isMainLine: true,
    tags: [],
    generation: 2,
    parentIds: ["richard-coy-1590"],
    spouseId: "elizabeth-roberts",
    notes: "Emigrated 1638 from Boston, Lincolnshire as part of John Whittingham's group migration. Traveled with brother Richard and sister Mary/Lucy after their father's death (will proved April 1638, Stamford, Lincolnshire). Ship unknown — the specific vessel has never been identified. Settled Ipswich, MA as an indentured servant to Atherton Hough (John Whittingham's stepfather); 1641 court record documents him as barber/servant to Hough. In 1654 he deposed he was 'aged about 33 years,' consistent with birth ~1621. Purchased Boston property from Elizabeth (Ann) Hibbins in 1656 — the same year she was executed for witchcraft; held the property through 1668. After wife Elizabeth Roberts died in 1668, moved family from Boston to Wenham, Essex County, MA. Death date uncertain: data.js uses 1677 (one source says 'after August 3, 1677'); other sources give 1675. Previous death place of 'Worcester, MA' appears to be an error — Wenham is the family's documented location. Son Richard Coy (b.1658) was killed at Quaboag, August 2, 1675, alongside uncle Richard Coy II — both Coy men lost in the same raid.",
  },
  {
    id: "elizabeth-roberts",
    name: "Elizabeth Roberts",
    birth: { year: 1618, place: "wales" },
    death: { year: 1668, place: "wenham" },
    isMainLine: false,
    tags: [],
    generation: 2,
    spouseId: "matthew-coy-i",
    notes: "Birth year disputed: GEDCOM gives 1616, other sources 1618. Birthplace uncertain: variously listed as Wales or Yorkshire, England — these are different regions; the discrepancy likely reflects an unresolved transcription error in an early source. Parentage unknown; arrival date in Massachusetts unrecorded. Marriage date disputed: June 29 vs. August 29, 1654, Boston, MA — both dates appear in sources and one is likely a misread. Died 1668 at Wenham, MA (~age 50). Her death is what prompted Matthew to relocate from Boston to Wenham with the children.",
  },
  {
    id: "lucy-mary-coy",
    name: "Mary Coy",
    birth: { year: 1612, place: "lincolnshire" },
    death: { year: 1678, place: "boston" },
    isMainLine: false,
    tags: [],
    generation: 2,
    parentIds: ["richard-coy-1590"],
    spouseId: "john-lake",
    notes: "Emigrated 1638 with brothers Matthew and Richard. Married John Lake, a tailor of Boston, c. August 1644. Children: Caleb (1645), Persis (1647), Mary (1649). Relationship confirmed: Matthew Coy I is listed as 'brother-in-law' in John Lake's will. Name: previously recorded as 'Lucy Coy' in some compiled genealogies — WikiTree Coy-161 (citing Hunt, NEHGR Jan 1959:236) confirms the name is Mary. Birth year per WikiTree Coy-161. Death date disputed: WikiTree gives ~1655; other sources give May 13, 1678 — unresolved.",
  },
  {
    id: "john-lake",
    name: "John Lake",
    birth: { year: 1618, place: null },
    death: { year: 1677, place: null },
    isMainLine: false,
    tags: [],
    generation: 2,
    spouseId: "lucy-mary-coy",
    notes: "Tailor of Boston. His will names Matthew Coy I as 'brother-in-law,' confirming Lucy/Mary Coy as Matthew's sister.",
  },
  {
    id: "richard-coy-ii",
    name: "Richard Coy (II)",
    birth: { year: 1625, place: "lincolnshire" },
    death: { year: 1675, place: "quaboag" },
    isMainLine: false,
    tags: [],
    generation: 2,
    parentIds: ["richard-coy-1590"],
    spouseId: "martha-hayfield",
    notes: "Emigrated 1638 with the Whittingham group; indentured to William Hubbard Sr. of Ipswich for ten years. Became a major figure at Quaboag (Brookfield), MA: Corporal of the Militia, Constable (sworn April 1668), member of the Prudential Committee (appointed May 1667), Town Measurer, and earned bounties for killing 14 wolves in two years. Purchased a substantial property at Quaboag (3 pounds 15 shillings — triple the average grant). Played a significant role in establishing the Quaboag grist mill (financed by John Pynchon, 1669). Killed August 2, 1675 in the ambush at New Braintree during King Philip's War alongside seven others (Sgt. Prichard, Sgt. Ayres, Zechariah Phillips, Timothy Farlow, Edward Coleborn, Samuel Smedly, Shadrach Hapgood). His nephew Richard Coy (son of Matthew I, b.1658) was also killed the same day. Survivors withstood a three-day siege at the Brookfield garrison house until Major Simon Willard arrived August 4 with 46 troops. Birth year note: data.js previously showed 1623 (same as Matthew I); corrected to ~1625 per RESEARCH.md.",
  },
  {
    id: "john-coy-quaboag",
    name: "John Coy",
    birth: { year: null, place: "quaboag" },
    death: { year: 1675, place: "quaboag" },
    isMainLine: false,
    tags: [],
    generation: 3,
    parentIds: ["richard-coy-ii"],
    notes: "Killed alongside his father Richard Coy II in the Quaboag ambush, August 2, 1675.",
  },
  {
    id: "martha-hayfield",
    name: "Martha Haffield",
    birth: { year: 1627, place: "suffolk_eng" },
    death: { year: 1694, place: "boston" },
    isMainLine: false,
    tags: [],
    generation: 2,
    spouseId: "richard-coy-ii",
    notes: "Born in Sudbury, Suffolk, England. Sailed to Boston as an 8-year-old on The Planter (1635) with her father Richard Haffield (54, currier), mother Martha Haffield (42), and four sisters. Married Richard Coy II before December 20, 1651. Her younger sister Rachel Haffield (b.~1629, also on The Planter aged ~6) later married Lawrence Clinton and became Rachel Clinton — she was arrested May 28, 1692 and imprisoned in Ipswich Gaol during the 1692 witchcraft hysteria. Her case was an Ipswich case, distinct from the core Salem Village outbreak; she was released January 3, 1693 and died destitute in early 1695. Note on naming: Martha's mother was also named Martha Haffield — sources naming Rachel's parents as 'Richard and Martha Haffield' refer to the mother, not to Martha who married Richard Coy II. Death date corrected: died August 14, 1694 at Boston, MA (previous data.js had 1668 — she outlived Richard II by 19 years, returning to Boston after the Quaboag settlement was destroyed).",
  },

  // ── Generation 3 ──────────────────────────────────────────
  {
    id: "richard-coy-1658",
    name: "Richard Coy",
    birth: { year: 1658, place: "boston" },
    death: { year: 1675, place: "quaboag" },
    isMainLine: false,
    tags: [],
    generation: 3,
    parentIds: ["matthew-coy-i"],
    notes: "Born September 6, 1658, Boston. Killed August 2, 1675 at the Quaboag ambush during King Philip's War, age ~16 — the same day and place as his uncle Richard Coy II. Death place corrected from 'norwich_ct' (an error) to 'quaboag.'",
  },
  {
    id: "john-coy-1666",
    name: "John Coy",
    birth: { year: 1666, place: "salisbury" },
    death: { year: 1737, place: "wenham" },
    isMainLine: false,
    tags: [],
    generation: 3,
    parentIds: ["matthew-coy-i"],
    notes: "Born September 2, 1666; settled Beverly, MA per research sources. Death year 1737 consistent with records; death place: data.js shows Wenham but the Barton genealogy (b3236.html) states he 'drowned in Virginia in 1737' — flagged as unresolved. Birth place may be Salisbury or Beverly area.",
  },
  {
    id: "samuel-coy-1667",
    name: "Samuel Coy",
    birth: { year: 1667, place: "preston_ct" },
    death: { year: 1740, place: "preston_ct" },
    isMainLine: false,
    tags: [],
    generation: 3,
    parentIds: ["matthew-coy-i"],
    spouseId: "lydia-billings-bromley",
    notes: null,
  },
  {
    id: "lydia-billings-bromley",
    name: "Lydia Billings Bromley",
    birth: { year: 1672, place: null },
    death: { year: 1747, place: null },
    isMainLine: false,
    tags: [],
    generation: 3,
    spouseId: "samuel-coy-1667",
    notes: null,
  },
  {
    id: "richard-coy-jr",
    name: "Richard Coy Jr.",
    birth: { year: 1656, place: "ipswich" },
    death: { year: 1738, place: "virginia" },
    isMainLine: false,
    tags: [],
    generation: 3,
    parentIds: ["richard-coy-ii"],
    spouseId: "sarah-kent",
    notes: "Son of Richard Coy II and Martha Haffield. Had multiple marriages: Sarah Kent, Sarah Littlefield, Rebecca Stanley, Miriam Babcock. Died Virginia, 1737–1738. Birth place corrected from 'Salisbury' to Ipswich area where Richard II was living in 1656.",
  },
  {
    id: "jabez-coy-1660",
    name: "Jabez Coy",
    birth: { year: 1660, place: "ipswich" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 3,
    parentIds: ["richard-coy-ii"],
    notes: "Born June 15, 1660, Ipswich, MA. Son of Richard Coy II and Martha Haffield.",
  },
  {
    id: "haffield-coy-1663",
    name: "Haffield Coy",
    birth: { year: 1663, place: "ipswich" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 3,
    parentIds: ["richard-coy-ii"],
    notes: "Son of Richard Coy II and Martha Haffield. Named for mother's Haffield family.",
  },
  {
    id: "caleb-coy-1666",
    name: "Caleb Coy",
    birth: { year: 1666, place: "boston" },
    death: { year: 1701, place: null },
    isMainLine: false,
    tags: [],
    generation: 3,
    parentIds: ["richard-coy-ii"],
    spouseId: "mary-wellman",
    notes: "Born August 16, 1666, Boston — family had relocated from Ipswich before his birth. Son of Richard Coy II and Martha Haffield.",
  },
  {
    id: "sarah-kent",
    name: "Sarah Kent",
    birth: { year: 1674, place: "brookfield" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 3,
    spouseId: "richard-coy-jr",
    notes: null,
  },
  {
    id: "sarah-littlefield",
    name: "Sarah Littlefield",
    birth: { year: 1674, place: "manchester_ma" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 3,
    spouseId: "richard-coy-jr",
    notes: null,
  },
  {
    id: "rebecca-stanley",
    name: "Rebecca Stanley",
    birth: { year: 1674, place: "beverly_ma" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 3,
    spouseId: "richard-coy-jr",
    notes: null,
  },
  {
    id: "miriam-babcock",
    name: "Miriam Babcock",
    birth: { year: 1674, place: "manchester_ma" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 3,
    spouseId: "richard-coy-jr",
    notes: null,
  },
  {
    id: "mary-wellman",
    name: "Mary Wellman",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 3,
    spouseId: "caleb-coy-1666",
    notes: "Second wife of Caleb Coy.",
  },
  {
    id: "martha-coy-1651",
    name: "Martha Coy",
    birth: { year: 1651, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 3,
    notes: null,
  },
  {
    id: "jabez-coy",
    name: "Jabez Coy",
    birth: { year: 1660, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 3,
    notes: null,
  },
  {
    id: "haffield-coy",
    name: "Haffield Coy",
    birth: { year: 1663, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 3,
    notes: null,
  },
  {
    id: "sarah-coy-1651",
    name: "Sarah Coy",
    birth: { year: 1651, place: "boston" },
    death: { year: null, place: "providence" },
    isMainLine: false,
    tags: [],
    generation: 3,
    parentIds: ["matthew-coy-i"],
    notes: null,
  },
  {
    id: "elizabeth-coy-1654",
    name: "Elizabeth Coy",
    birth: { year: 1654, place: "boston" },
    death: { year: 1741, place: "worcester_ma" },
    isMainLine: false,
    tags: [],
    generation: 3,
    parentIds: ["matthew-coy-i"],
    notes: null,
  },
  // ── Brewster branch — Ann Brewster's Mayflower ancestry ─────────────────────
  {
    id: "william-brewster-mayflower",
    name: "William Brewster",
    birth: { year: 1566, place: "scrooby" },
    death: { year: 1644, place: "duxbury_ma" },
    isMainLine: false,
    tags: ["mayflower"],
    generation: 1,
    spouseId: "mary-brewster",
    notes: "Ruling Elder of the Pilgrim congregation; 4th of 41 signatories of the Mayflower Compact (1620). Born Scrooby, Nottinghamshire — the Scrooby Separatists founded Plymouth Colony. Led the congregation from England through the Netherlands (Leiden) to Plymouth. Great-great-grandfather of our Jonathan Coy (b.1687).",
  },
  {
    id: "mary-brewster",
    name: "Mary Brewster",
    birth: { year: 1568, place: "scrooby" },
    death: { year: 1627, place: "plymouth" },
    isMainLine: false,
    tags: [],
    generation: 1,
    spouseId: "william-brewster-mayflower",
    notes: "Wife of William Brewster; sailed on the Mayflower 1620. Maiden name unknown. Died Plymouth Colony, 1627.",
  },
  {
    id: "jonathan-brewster-1593",
    name: "Jonathan Brewster",
    birth: { year: 1593, place: "scrooby" },
    death: { year: 1659, place: "norwich_ct" },
    isMainLine: false,
    tags: [],
    generation: 2,
    parentIds: ["william-brewster-mayflower"],
    spouseId: "lucretia-oldham",
    notes: "Eldest son of William Brewster (Mayflower Elder). Arrived Plymouth on the Fortune, 1621 — one year after the Mayflower. Married Lucretia Oldham, April 10, 1624, Plymouth. Moved to Connecticut ~1649; became town clerk of Pequot (New London). Obtained grant from Sachem Uncas of the Mohegan; confirmed November 30, 1652 as 'Brewster's Neck' in Preston CT — used as an Indian trading post. Buried at Brewster Cemetery, Brewster's Neck, Preston CT. Grandfather of Ann Brewster who married Matthew Coy II.",
  },
  {
    id: "lucretia-oldham",
    name: "Lucretia Oldham",
    birth: { year: 1600, place: "england" },
    death: { year: 1678, place: "norwich_ct" },
    isMainLine: false,
    tags: [],
    generation: 2,
    spouseId: "jonathan-brewster-1593",
    notes: "Born Derby, Derbyshire, England. Married Jonathan Brewster April 10, 1624, Plymouth Colony.",
  },
  {
    id: "benjamin-brewster-1633",
    name: "Benjamin Brewster",
    birth: { year: 1633, place: "norwich_ct" },
    death: { year: 1710, place: "norwich_ct" },
    isMainLine: false,
    tags: [],
    generation: 3,
    parentIds: ["jonathan-brewster-1593"],
    spouseId: "ann-addis-dart",
    notes: "Son of Jonathan Brewster (Mayflower line); born and raised at Brewster's Neck. Captain of the Military Company of Norwich, 1693; served as deputy and commissioner of Connecticut Colony. Married Ann (Addis) Dart, February 28, 1660, Norwich CT. Father of Ann Brewster who married Matthew Coy II. Primary source: Norwich vital records; Merrick, Mayflower Families through Five Generations (2014).",
  },
  {
    id: "ann-addis-dart",
    name: "Ann (Addis) Dart",
    birth: { year: 1628, place: "frampton_gl" },
    death: { year: 1709, place: "norwich_ct" },
    isMainLine: false,
    tags: [],
    generation: 3,
    spouseId: "benjamin-brewster-1633",
    notes: "Born Frampton, Gloucestershire, England. Previously married to Ambrose Dart. Married Benjamin Brewster February 28, 1660, Norwich CT. Mother of Ann Brewster who married Matthew Coy II.",
  },
  {
    id: "matthew-coy-ii",
    name: "Matthew Coy II",
    birth: { year: 1656, place: "boston" },
    death: { year: 1715, place: "stafford_ct" },
    isMainLine: true,
    tags: [],
    generation: 3,
    parentIds: ["matthew-coy-i"],
    spouseId: "ann-brewster",
    notes: "Born September 5, 1656, Boston, MA — same year Matthew Coy I purchased the Hibbins property in Boston. Settled Preston/Norwich CT area. Married Ann Brewster ~1684. Both Matthew and Ann died on October 30, 1715 — the same day. Matthew's death is recorded in Stafford, Tolland County CT (40 miles from Preston); Ann's in Preston. The conflicting death locations may reflect a source error or that one was traveling. Most likely cause: epidemic disease; Connecticut experienced severe smallpox and fever outbreaks in 1713–1716.",
  },
  {
    id: "ann-brewster",
    name: "Ann Brewster",
    birth: { year: 1662, place: "duxbury_ma" },
    death: { year: 1715, place: "preston_ct" },
    isMainLine: false,
    tags: [],
    generation: 3,
    parentIds: ["benjamin-brewster-1633"],
    spouseId: "matthew-coy-ii",
    notes: "Born September 29, 1662, Duxbury, Plymouth Colony. Great-granddaughter of William Brewster (Mayflower Elder, 1620). Lineage: William Brewster → Jonathan Brewster → Benjamin Brewster → Ann Brewster. Grew up on Brewster's Neck, land her grandfather Jonathan purchased from Sachem Uncas in 1652. Died October 30, 1715, Preston CT — the same day as her husband Matthew Coy II. Primary source: WikiTree Brewster-20; Merrick, Mayflower Families through Five Generations (2014).",
  },

  // ── Generation 4 ──────────────────────────────────────────
  {
    id: "elizabeth-coy-1708",
    name: "Elizabeth Coy",
    birth: { year: 1702, place: "norwich_ct" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 4,
    parentIds: ["matthew-coy-ii"],
    notes: "Birth corrected to August 30, 1702, Norwich CT per WikiTree Brewster-20 (previously recorded as 1708, MA — error).",
  },
  {
    id: "daniel-coy-1685",
    name: "Daniel Coy",
    birth: { year: 1685, place: "norwich_ct" },
    death: { year: 1766, place: "griswold_ct" },
    isMainLine: false,
    tags: [],
    generation: 4,
    parentIds: ["matthew-coy-ii"],
    notes: null,
  },
  {
    id: "ruth-coy-1689",
    name: "Ruth Coy",
    birth: { year: 1689, place: "norwich_ct" },
    death: { year: 1752, place: "new_london_ct" },
    isMainLine: false,
    tags: [],
    generation: 4,
    parentIds: ["matthew-coy-ii"],
    spouseId: "samuel-atwell",
    notes: null,
  },
  {
    id: "samuel-atwell",
    name: "Samuel Atwell",
    birth: { year: 1682, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 4,
    spouseId: "ruth-coy-1689",
    notes: null,
  },
  {
    id: "mary-coy-1693",
    name: "Mary Coy",
    birth: { year: 1701, place: "norwich_ct" },
    death: { year: 1752, place: "new_london_ct" },
    isMainLine: false,
    tags: [],
    generation: 4,
    parentIds: ["matthew-coy-ii"],
    notes: "Birth corrected to November 1701, Norwich CT per WikiTree Brewster-20 (previously recorded as 1693 Plymouth — error).",
  },
  {
    id: "samuel-coy-sr-1695",
    name: "Samuel Coy Sr.",
    birth: { year: 1695, place: "norwich_ct" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 4,
    parentIds: ["matthew-coy-ii"],
    notes: "Born 1695, Mohegan/Norwich, CT. Son of Matthew Coy II and Ann Brewster. Added per WikiTree Brewster-20.",
  },
  {
    id: "jonathan-coy-1687",
    name: "Jonathan Coy",
    birth: { year: 1687, place: "norwich_ct" },
    death: { year: 1766, place: "preston_ct" },
    isMainLine: true,
    tags: [],
    generation: 4,
    parentIds: ["matthew-coy-ii"],
    spouseId: "abigail-unknown-coy",
    notes: "Born May 6, 1687, Norwich CT; died February 10, 1766, Preston CT. Son of Matthew Coy II and Ann Brewster. Father of John L. Coy I (b.1725) — confirmed by Gale Ion Harris, 'Early Coy and Harris Families of Eastern Connecticut,' NEHGR Vol. 168, p.69 (2014). 10 documented children baptized in Preston CT. This is the correct generational link between Matthew Coy II and Christopher Coy's grandfather.",
  },
  {
    id: "abigail-unknown-coy",
    name: "Abigail Coy",
    birth: { year: null, place: null },
    death: { year: 1767, place: "griswold_ct" },
    isMainLine: false,
    tags: [],
    generation: 4,
    spouseId: "jonathan-coy-1687",
    notes: "Wife of Jonathan Coy; maiden name unknown. Death record: Griswold, CT, June 12, 1767.",
  },
  {
    id: "matthew-coy-iii",
    name: "Matthew Coy III",
    birth: { year: 1692, place: "norwich_ct" },
    death: { year: 1783, place: "stonington_ct" },
    isMainLine: false,
    tags: [],
    generation: 4,
    parentIds: ["matthew-coy-ii"],
    spouseId: "sarah-welch-coy",
    notes: "Brother of Jonathan Coy (1687-1766). Previously incorrectly listed as father of John L. Coy I — corrected per NEHGR Vol. 168 (2014). His own son John (b.1730, Stonington CT) is a different person from John L. Coy I (b.1725, Preston CT). Birth year corrected from 1694 to ~1692; birth place corrected from beverly_ma (his wife's birthplace) to Norwich, CT.",
  },
  {
    id: "sarah-welch-coy",
    name: "Sarah Welch Coy",
    birth: { year: 1698, place: "beverly_ma" },
    death: { year: 1791, place: "stonington_ct" },
    isMainLine: false,
    tags: [],
    generation: 4,
    spouseId: "matthew-coy-iii",
    notes: "Wife of Matthew Coy III. Born Beverly, MA — her birthplace was previously confused with Matthew's in the data.",
  },
  {
    id: "samuel-coy-1698",
    name: "Samuel Coy",
    birth: { year: 1698, place: "norwich_ct" },
    death: { year: 1776, place: "hartford_ct" },
    isMainLine: false,
    tags: [],
    generation: 4,
    parentIds: ["matthew-coy-ii"],
    spouseId: "elizabeth-read",
    notes: null,
  },
  {
    id: "elizabeth-read",
    name: "Elizabeth Read",
    birth: { year: 1698, place: null },
    death: { year: 1766, place: null },
    isMainLine: false,
    tags: [],
    generation: 4,
    spouseId: "samuel-coy-1698",
    notes: null,
  },

  // ── Generation 5 ──────────────────────────────────────────
  {
    id: "abijah-coy",
    name: "Abijah Coy",
    birth: { year: 1721, place: "preston_ct" },
    death: { year: 1764, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["matthew-coy-iii"],
    notes: null,
  },
  {
    id: "daniel-coy-1722",
    name: "Daniel Coy",
    birth: { year: 1722, place: "preston_ct" },
    death: { year: 1792, place: "nelson_ky" },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["matthew-coy-iii"],
    notes: null,
  },
  {
    id: "matthew-coy-iv",
    name: "Matthew Coy IV",
    birth: { year: 1725, place: "preston_ct" },
    death: { year: 1784, place: "preston_ct" },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["matthew-coy-iii"],
    spouseId: "sarah-hewitt",
    notes: null,
  },
  {
    id: "sarah-hewitt",
    name: "Sarah Hewitt",
    birth: { year: 1729, place: "stonington_ct" },
    death: { year: 1810, place: "chenango_ny" },
    isMainLine: false,
    tags: [],
    generation: 5,
    spouseId: "matthew-coy-iv",
    notes: null,
  },
  {
    id: "benjamin-coy-1723",
    name: "Benjamin Coy",
    birth: { year: 1723, place: "preston_ct" },
    death: { year: null, place: "nelson_ky" },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["matthew-coy-iii"],
    notes: null,
  },
  {
    id: "abigail-coy-1731",
    name: "Abigail Coy",
    birth: { year: 1731, place: "stonington_ct" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["matthew-coy-iii"],
    notes: null,
  },
  {
    id: "samuel-coye-1721",
    name: "Samuel Coy",
    birth: { year: 1721, place: "preston_ct" },
    death: { year: 1764, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["matthew-coy-iii"],
    notes: null,
  },
  {
    id: "elizabeth-coy-1732",
    name: "Elizabeth Coy",
    birth: { year: 1732, place: "stonington_ct" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["matthew-coy-iii"],
    notes: null,
  },
  {
    id: "abraham-coy-1719",
    name: "Abraham Coy",
    birth: { year: 1719, place: "norwich_ct" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    notes: null,
  },
  {
    id: "zipporah-coy",
    name: "Zipporah Coy",
    birth: { year: 1721, place: "norwich_ct" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    notes: null,
  },
  {
    id: "samuel-coy-1723",
    name: "Samuel Coy",
    birth: { year: 1723, place: "norwich_ct" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    notes: null,
  },
  {
    id: "elizabeth-coy-1726",
    name: "Elizabeth Coy",
    birth: { year: 1726, place: "norwich_ct" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    notes: null,
  },
  {
    id: "john-l-coy-i",
    name: "John L. Coy I",
    birth: { year: 1725, place: "preston_ct" },
    death: { year: 1787, place: "hardin_ky" },
    isMainLine: true,
    tags: ["vet"],
    generation: 5,
    parentIds: ["jonathan-coy-1687"],
    spouseId: "sarah-woodbury",
    notes: "Baptized July 18, 1725, Preston CT. Son of Jonathan Coy (1687-1766) — confirmed by Gale Ion Harris, 'Early Coy and Harris Families of Eastern Connecticut,' NEHGR Vol. 168, p.69 (2014). Married 27 Oct 1745 at Bristol, RI to Sarah Woodbury. Migrated to Somerset County, MD by 1770. Served in the Maryland Militia, 2nd Class alongside John Marshall Sr. (1740–1801). Both families migrated together to Nelson County, KY; adjacent land along Rolling Fork and Younger's Creek. His daughter Rebecca Coy married Mark Marshall Sr. on May 26, 1788, in Bardstown, KY. Died of cholera 1787. Parentage previously listed as Matthew Coy III (his uncle, not father) — corrected. German Jacob Coy theory ruled out by NEHGR documentation. See RESEARCH.md Section 20.",
  },
  {
    id: "sarah-woodbury",
    name: "Sarah Woodbury",
    birth: { year: 1723, place: "bristol_ri" },
    death: { year: 1787, place: "garrard_ky" },
    isMainLine: false,
    tags: [],
    generation: 5,
    spouseId: "john-l-coy-i",
    notes: "Died of cholera along with husband John and their son.",
  },

  // ── Generation 5 (siblings of John L. Coy I — children of Jonathan Coy) ──
  {
    id: "jonathan-coy-jr",
    name: "Jonathan Coy Jr.",
    birth: { year: 1720, place: "preston_ct" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["jonathan-coy-1687"],
    notes: "Baptized February 26, 1720, Preston CT. Eldest child of Jonathan Coy and Abigail. No marriage or death records found in accessible sources.",
  },
  {
    id: "samuel-coy-1721",
    name: "Samuel Coy",
    birth: { year: 1721, place: "preston_ct" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["jonathan-coy-1687"],
    notes: "Baptized February 26, 1721, Preston CT — same date as Abijah, likely twins. No further records confirmed.",
  },
  {
    id: "abijah-coye",
    name: "Abijah Coye",
    birth: { year: 1721, place: "preston_ct" },
    death: { year: 1783, place: "maine" },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["jonathan-coy-1687"],
    spouseId: "ruth-wedge",
    notes: "Baptized February 1721, Preston CT. Married (1) Ruth Wedge, July 8, 1740, Griswold CT; (2) Judith Luce. Died Maine, 1783. Migrated northeast while brothers John moved southwest toward Maryland and Kentucky. Surname often recorded 'Coye' in CT records.",
  },
  {
    id: "ruth-wedge",
    name: "Ruth Wedge",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    spouseId: "abijah-coye",
    notes: "First wife of Abijah Coye. Married July 8, 1740, Griswold, CT.",
  },
  {
    id: "mary-coy-1721",
    name: "Mary Coy",
    birth: { year: 1721, place: "preston_ct" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["jonathan-coy-1687"],
    notes: "Baptized October 22, 1721, Preston CT. Preston/Griswold records list 'Thomas Springer of Voluntown married Sarah Coy, Jan 10, 1738/9' — possibly this Mary under a variant given name, or a separate daughter absent from the baptism record.",
  },
  {
    id: "moses-coy-1723",
    name: "Moses Coy",
    birth: { year: 1723, place: "preston_ct" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["jonathan-coy-1687"],
    notes: "Baptized October 13, 1723, Preston CT. Possible ancestor of Coy descendants documented in Chenango County, NY in later generations. No marriage or death record confirmed.",
  },
  {
    id: "john-h-coy-sr",
    name: "John H. Coy Sr.",
    birth: { year: 1725, place: "preston_ct" },
    death: { year: 1792, place: "nelson_ky" },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["jonathan-coy-1687"],
    spouseId: "sarah-luce",
    notes: "Baptized July 18, 1725, Preston CT — same baptism date as John L. Coy I. WikiTree Coy-412. Married (1) Sarah Luce, Jan 9, 1749/50, Griswold CT; (2) Miriam Murdock, March 8, 1764, Griswold CT; (3) Tenny Unknown. Died 1792, Nelson County, KY — directly adjacent to Hardin/Garrard where John L. Coy I died in 1787. Both brothers migrated to the same Kentucky county cluster, almost certainly together. The identical baptism date with John L. Coy I is unusual; different marriages, death years, and death places confirm they are distinct individuals.",
  },
  {
    id: "sarah-luce",
    name: "Sarah Luce",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    spouseId: "john-h-coy-sr",
    notes: "First wife of John H. Coy Sr. Married Jan 9, 1749/50, Griswold, CT.",
  },
  {
    id: "matthew-coy-1727",
    name: "Matthew Coy",
    birth: { year: 1727, place: "preston_ct" },
    death: { year: 1783, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["jonathan-coy-1687"],
    spouseId: "amy-church",
    notes: "Baptized April 7, 1727, Preston CT. Married Amy Church. FamilySearch ID LZ6H-H34, dates 1727–1783. Likely remained in New England — no western migration documented.",
  },
  {
    id: "amy-church",
    name: "Amy Church",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    spouseId: "matthew-coy-1727",
    notes: null,
  },
  {
    id: "nathaniel-coy-1728",
    name: "Nathaniel Coy",
    birth: { year: 1728, place: "preston_ct" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["jonathan-coy-1687"],
    notes: "Baptized March 9, 1728/9, Preston CT. No further records confirmed.",
  },
  {
    id: "abigail-coy-1731-jonathan",
    name: "Abigail Coy",
    birth: { year: 1731, place: "preston_ct" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["jonathan-coy-1687"],
    notes: "Baptized November 8, 1731, Preston CT. Named for her mother Abigail. No further records confirmed.",
  },
  {
    id: "joseph-coy-1735",
    name: "Joseph Coy",
    birth: { year: 1735, place: "preston_ct" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["jonathan-coy-1687"],
    notes: "Baptized 1735, Preston CT. Youngest of Jonathan Coy's documented children. No further records confirmed.",
  },

  // ── Generation 6 ──────────────────────────────────────────
  {
    id: "christopher-coy",
    name: "Christopher Coy",
    birth: { year: 1751, place: "somerset_md" },
    death: { year: 1839, place: "lawrence_il" },
    isMainLine: true,
    tags: ["vet"],
    generation: 6,
    parentIds: ["john-l-coy-i"],
    spouseId: "elizabeth-tucker",
    notes: "Revolutionary War veteran: private in the Maryland Continental Line under Capt. Henry Gaither, 7th Regiment (Col. William Smallwood). Enlisted spring 1779 in Maryland; served through Cornwallis's surrender Oct 19, 1781; honorably discharged. Pension file W9798, NARA M804 Maryland series (transcription at ~/coy-tree-tracker/w9798.pdf). DAR Ancestor #A027112. Birth year discrepancy: DAR says 1751, but his 1821 pension declaration states he was 'sixty years' old, implying b.~1761 — a 10-year gap; flagged as unresolved. Migration trail (primary sources): Frederick Co. MD (1790 census) → Madison Co. KY (1810, 1820 census; pension filed 1821) → Harrison Co. IN (March 1828, pension transfer — moved 'to accompany his children who are generally settled in the neighborhood') → Washington Co. IN (Oct 1831 — affidavit in brother William David's pension) → Lawrence Co. IL (d. Oct 12, 1839). Wife filed widow's pension Nov 15, 1839 from Parke County, Indiana (she was in Indiana when Christopher died in Illinois). Buried Spring Hill Cemetery, Bridgeport, Lawrence County, IL. Assets in 1821: 1 cow, 1 yearling, 304 hogs, 2 sheep, 1 plow, household furniture (court-valued at $35 — undervalued to qualify for pension). Children named in pension file: John Coy (b.~1793, aged 47 in 1840), Samuel (b.~1780, aged 60 in 1840), Anna/Amy Smith (b.~1777–78, aged 65–66 in 1843 in Lawrence Co. IL). John stated 3 brothers and 3 sisters still living in 1840 — minimum 9 children survived to 1840. Stephen Coy not named in file but could be among unnamed siblings; parentage unconfirmed. Wife's maiden name Tucker is NOT stated in the pension file. DAR record warns: 'PROBLEMS HAVE BEEN DISCOVERED WITH AT LEAST ONE PREVIOUSLY VERIFIED PAPER; FUTURE APPLICANTS MUST PROVE CORRECT LINEAGE.' See RESEARCH.md Sections 14, 20, 25, and 26.",
  },
  {
    id: "elizabeth-tucker",
    name: "Elizabeth Tucker",
    birth: { year: 1754, place: "appomattox_va" },
    death: { year: 1847, place: "lawrence_il" },
    isMainLine: false,
    tags: [],
    generation: 6,
    spouseId: "christopher-coy",
    notes: "Married Christopher Coy on April 15, 1773 (pension file shows various dates: April 12 or 15, 1773, 1775, or 1776; exact date unresolved). Maiden name 'Tucker' is NOT stated in the pension file W9798 and is unconfirmed — the transcriber of W9798 explicitly notes 'the maiden name of the widow is not stated.' Filed widow's pension November 15, 1839, from Parke County, Indiana (not Lawrence County, IL where Christopher died — she was with other family in Indiana). Was 85 years old at filing. Died 1847, Lawrence County, IL per other sources.",
  },
  {
    id: "john-coy-ii",
    name: "John Coy II",
    birth: { year: 1746, place: "somerset_md" },
    death: { year: 1817, place: "hardin_ky" },
    isMainLine: false,
    tags: [],
    generation: 6,
    parentIds: ["john-l-coy-i"],
    spouseId: "sarah-ann-comfort",
    notes: null,
  },
  {
    id: "sarah-ann-comfort",
    name: "Sarah Ann Comfort",
    birth: { year: 1754, place: "hardin_ky" },
    death: { year: 1830, place: "hardin_ky" },
    isMainLine: false,
    tags: [],
    generation: 6,
    spouseId: "john-coy-ii",
    notes: null,
  },
  {
    id: "daniel-coy-1749",
    name: "Daniel Coy",
    birth: { year: 1749, place: "preston_ct" },
    death: { year: 1820, place: "arlington_vt" },
    isMainLine: false,
    tags: [],
    generation: 6,
    notes: null,
  },
  {
    id: "elisha-ephraim-coy",
    name: "Elisha Coy",
    birth: { year: 1763, place: "stonington_ct" },
    death: { year: 1843, place: "new_hudson_ny" },
    isMainLine: false,
    tags: [],
    generation: 5,
    parentIds: ["matthew-coy-iii"],
    notes: "Listed as Elisha (Ephraim?) Coy in source.",
  },
  {
    id: "freelove-coy",
    name: "Freelove Coy",
    birth: { year: 1771, place: "preston_ct" },
    death: { year: null, place: "ny" },
    isMainLine: false,
    tags: [],
    generation: 6,
    notes: null,
  },
  {
    id: "sarah-coy-1772",
    name: "Sarah Coy",
    birth: { year: 1772, place: "stonington_ct" },
    death: { year: 1820, place: "genoa_ny" },
    isMainLine: false,
    tags: [],
    generation: 6,
    notes: null,
  },
  {
    id: "lucy-coy-1754",
    name: "Lucy Coy",
    birth: { year: 1754, place: "chenango_ny" },
    death: { year: 1826, place: "norfolk_ct" },
    isMainLine: false,
    tags: [],
    generation: 6,
    notes: null,
  },
  {
    id: "benjamin-coy-1756",
    name: "Benjamin Coy",
    birth: { year: 1756, place: "middletown_vt" },
    death: { year: 1765, place: "middletown_vt" },
    isMainLine: false,
    tags: [],
    generation: 6,
    notes: null,
  },
  {
    id: "anna-coy-1760",
    name: "Anna Coy",
    birth: { year: 1760, place: "stonington_ct" },
    death: { year: 1810, place: "norfolk_ct" },
    isMainLine: false,
    tags: [],
    generation: 6,
    notes: null,
  },
  {
    id: "ephraim-coy-1762",
    name: "Ephraim Coy",
    birth: { year: 1762, place: "preston_ct" },
    death: { year: 1834, place: "litchfield_ct" },
    isMainLine: false,
    tags: [],
    generation: 6,
    notes: null,
  },
  {
    id: "elisha-coy-1763",
    name: "Elisha Coy",
    birth: { year: 1763, place: "preston_ct" },
    death: { year: 1840, place: "chenango_ny" },
    isMainLine: false,
    tags: [],
    generation: 6,
    notes: null,
  },
  {
    id: "levi-coy",
    name: "Levi Coy",
    birth: { year: 1765, place: "norfolk_ct" },
    death: { year: null, place: "locke_ny" },
    isMainLine: false,
    tags: [],
    generation: 6,
    notes: null,
  },
  {
    id: "delana-coy",
    name: "Delana Coy",
    birth: { year: 1767, place: "norfolk_ct" },
    death: { year: 1830, place: "locke_ny" },
    isMainLine: false,
    tags: [],
    generation: 6,
    notes: null,
  },
  {
    id: "simeon-coy",
    name: "Simeon Coy",
    birth: { year: 1768, place: "chenango_ny" },
    death: { year: 1832, place: "norfolk_ct" },
    isMainLine: false,
    tags: [],
    generation: 6,
    notes: null,
  },
  {
    id: "elkanah-coy",
    name: "Elkanah Coy",
    birth: { year: 1773, place: "stonington_ct" },
    death: { year: 1845, place: "torrington_ct" },
    isMainLine: false,
    tags: [],
    generation: 6,
    notes: "Twin.",
  },
  {
    id: "hannah-coy-1773",
    name: "Hannah Coy",
    birth: { year: 1773, place: "stonington_ct" },
    death: { year: 1848, place: "norfolk_ct" },
    isMainLine: false,
    tags: [],
    generation: 6,
    notes: "Twin.",
  },
  {
    id: "samuel-coy-1748",
    name: "Samuel Coy",
    birth: { year: 1748, place: "bristol_ri" },
    death: { year: 1824, place: "madison_ky" },
    isMainLine: false,
    tags: ["vet"],
    generation: 6,
    parentIds: ["john-l-coy-i"],
    spouseId: "mary-pearse",
    notes: null,
  },
  {
    id: "mary-pearse",
    name: "Mary Pearse",
    birth: { year: null, place: "bristol_ri" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 6,
    spouseId: "samuel-coy-1748",
    notes: null,
  },
  {
    id: "sarah-coy-danforth",
    name: "Sarah (Coy) Danforth",
    birth: { year: 1752, place: "bristol_ri" },
    death: { year: 1811, place: "providence" },
    isMainLine: false,
    tags: [],
    generation: 6,
    parentIds: ["john-l-coy-i"],
    spouseId: "job-danforth",
    notes: null,
  },
  {
    id: "job-danforth",
    name: "Job Danforth",
    birth: { year: 1745, place: "bristol_ma" },
    death: { year: 1838, place: "providence" },
    isMainLine: false,
    tags: [],
    generation: 6,
    spouseId: "sarah-coy-danforth",
    notes: null,
  },
  {
    id: "william-david-coy-sr",
    name: "William David Coy Sr.",
    birth: { year: 1756, place: "somerset_md" },
    death: { year: 1833, place: "vevay_in" },
    isMainLine: false,
    tags: ["vet"],
    generation: 6,
    parentIds: ["john-l-coy-i"],
    spouseId: "mary-ann-dennis",
    notes: "Revolutionary War veteran: DAR Ancestor #A027119. Enlisted July 1777, Montgomery County, MD; served under Capt. Nathaniel Pigman, Col. Mordock, 7th Regiment Maryland Militia; participated in the Battle of Germantown. Drafted October 1781 for a second term as a guard over Cornwallis's captured Hessians at Frederickstown, MD. Applied for pension in 1832 under the Act of June 7, 1832. In his application he acknowledged no surviving documentary proof of service and cited a supporting affidavit from his brother Christopher Coy, then residing in Washington County, Indiana (dated October 25, 1831). From his own pension deposition, his migration after the Revolution: lived in Montgomery County, MD ~8 years → moved to the James River, VA ~20 years → moved to Garrard County, KY ~20 years → moved to Indiana ~6 years (so arrived Indiana ~1826–1827). Married Mary Ann Dennis on November 25, 1779, Montgomery County, MD; 12 documented children. Possible second marriage to Lener Chandler (1824, Madison County, KY per original tree data — unconfirmed). Buried Hominy Ridge, York Township, Switzerland County, IN (Ted Carver farm). Source: Robert L. Kelley, The Scotts of Hominy Ridge (2000), p.25; pension deposition in NARA M804 file.",
  },
  {
    id: "lener-chandler",
    name: "Lener Chandler",
    birth: { year: null, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 6,
    notes: "Possible second wife of William David Coy Sr. (married 1824 per original Figma tree data, Madison County KY). Unconfirmed — William David's pension application and biographical sources name only Mary Ann Dennis as his wife. Retained from original source data pending verification.",
  },
  {
    id: "mary-ann-dennis",
    name: "Mary Ann Dennis",
    birth: { year: 1760, place: "montgomery_md" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 6,
    spouseId: "william-david-coy-sr",
    notes: "Married William David Coy Sr. on November 25, 1779, Montgomery County, Maryland. 12 documented children: Thomas B., Susannah 'Sukey,' Elizabeth Ann, Samuel, Esther 'Hessy,' Sarah Sally, Betsy, William Jr., Celia, Mary, Frances, Nancy. Birth year estimated from marriage year.",
  },
  {
    id: "jonathon-woodbury-coy",
    name: "Jonathon Woodbury Coy",
    birth: { year: 1757, place: "bristol_ri" },
    death: { year: 1811, place: "barrington_ri" },
    isMainLine: false,
    tags: [],
    generation: 6,
    parentIds: ["john-l-coy-i"],
    spouseId: "elizabeth-peckham",
    notes: null,
  },
  {
    id: "elizabeth-peckham",
    name: "Elizabeth Peckham",
    birth: { year: 1764, place: "newport_ri" },
    death: { year: 1803, place: "providence" },
    isMainLine: false,
    tags: [],
    generation: 6,
    spouseId: "jonathon-woodbury-coy",
    notes: null,
  },
  {
    id: "william-coy-1750",
    name: "William Coy",
    birth: { year: 1750, place: "bristol_ri" },
    death: { year: null, place: "madison_ky" },
    isMainLine: false,
    tags: ["vet"],
    generation: 6,
    parentIds: ["john-l-coy-i"],
    spouseId: "ruth-savery",
    notes: null,
  },
  {
    id: "ruth-savery",
    name: "Ruth Savery",
    birth: { year: 1755, place: "plymouth" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 6,
    spouseId: "william-coy-1750",
    notes: null,
  },

  // ── Generation 7 ──────────────────────────────────────────
  {
    id: "anna-maria-coy-smith",
    name: "Anna Maria (Coy) Smith",
    birth: { year: 1776, place: "frederick_md" },
    death: { year: 1843, place: "lawrence_il" },
    isMainLine: false,
    tags: [],
    generation: 7,
    parentIds: ["christopher-coy"],
    spouseId: "nicholas-smith",
    notes: null,
  },
  {
    id: "nicholas-smith",
    name: "Nicholas Smith",
    birth: { year: 1795, place: "maryland" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 7,
    spouseId: "anna-maria-coy-smith",
    notes: null,
  },
  {
    id: "elizabeth-betsy-coy-neff",
    name: 'Elizabeth "Betsy" (Coy) Neff',
    birth: { year: 1792, place: "amherst_va" },
    death: { year: 1892, place: "lawrence_il" },
    isMainLine: false,
    tags: [],
    generation: 7,
    parentIds: ["christopher-coy"],
    spouseId: "benjamin-melton",
    notes: "Lived to approximately age 100.",
  },
  {
    id: "benjamin-melton",
    name: "Benjamin F. Melton",
    birth: { year: 1764, place: null },
    death: { year: 1845, place: null },
    isMainLine: false,
    tags: [],
    generation: 7,
    spouseId: "elizabeth-betsy-coy-neff",
    notes: null,
  },
  {
    id: "rebecca-coy-marshall",
    name: "Rebecca (Coy) Marshall",
    birth: { year: 1766, place: "washington_md" },
    death: { year: 1812, place: "nelson_ky" },
    isMainLine: false,
    tags: [],
    generation: 6,
    parentIds: ["john-l-coy-i"],
    spouseId: "mark-marshall-sr",
    notes: "Daughter of John L. Coy I and Sarah Woodbury. Married Mark Marshall Sr. on May 26, 1788, in Bardstown, Nelson County, KY. The Coy and Marshall families migrated to Kentucky together after their fathers — John L. Coy I and John Marshall Sr. — had served in the same Maryland Militia unit during the Revolution.",
  },
  {
    id: "mark-marshall-sr",
    name: "Mark Marshall Sr.",
    birth: { year: 1765, place: "frederick_md" },
    death: { year: 1823, place: "new_haven_ky" },
    isMainLine: false,
    tags: [],
    generation: 6,
    spouseId: "rebecca-coy-marshall",
    notes: "Son of John Marshall Sr. (1740–1801, Maryland Militia) and Deborah Chambers. NOT a sibling of Chief Justice John Marshall — that line descends from Colonel Thomas Marshall of Fauquier County, VA, a distinct family. John Marshall Sr. and John L. Coy I served in the same Maryland Militia, 2nd Class unit during the Revolution; both families migrated to Nelson County, KY afterward and held adjacent land. Mark received a 376-acre land grant along Rolling Fork, Nelson County, in 1786. His father John Marshall Sr. died in Nelson County, 1801.",
  },
  {
    id: "daniel-coy-1767",
    name: "Daniel Coy",
    birth: { year: 1767, place: "somerset_md" },
    death: { year: 1839, place: "larue_ky" },
    isMainLine: false,
    tags: [],
    generation: 6,
    parentIds: ["john-l-coy-i"],
    notes: null,
  },
  {
    id: "matthew-benjamin-coy",
    name: "Matthew Benjamin Coy",
    birth: { year: 1772, place: "washington_md" },
    death: { year: 1844, place: "madison_wi" },
    isMainLine: false,
    tags: [],
    generation: 6,
    parentIds: ["john-l-coy-i"],
    notes: null,
  },
  {
    id: "huldy-coy",
    name: "Huldy Coy",
    birth: { year: 1778, place: "washington_md" },
    death: { year: 1805, place: "indiana" },
    isMainLine: false,
    tags: [],
    generation: 6,
    parentIds: ["john-l-coy-i"],
    notes: null,
  },
  {
    id: "phoebe-coy-van-winkle",
    name: "Phoebe (Coy) Van Winkle",
    birth: { year: 1779, place: "nelson_ky" },
    death: { year: 1826, place: "rome_city_in" },
    isMainLine: false,
    tags: [],
    generation: 6,
    parentIds: ["john-l-coy-i"],
    notes: null,
  },
  {
    id: "benjamin-benedict-coy",
    name: "Benjamin Benedict Coy",
    birth: { year: 1781, place: "washington_md" },
    death: { year: 1855, place: "wassenville_ia" },
    isMainLine: false,
    tags: [],
    generation: 6,
    parentIds: ["john-l-coy-i"],
    notes: null,
  },
  {
    id: "charles-coy-1775",
    name: "Charles Coy",
    birth: { year: 1775, place: "indiana" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 7,
    parentIds: ["christopher-coy"],
    notes: null,
  },
  {
    id: "samuel-christopher-coy",
    name: "Samuel Christopher Coy",
    birth: { year: 1777, place: "montgomery_md" },
    death: { year: 1846, place: "howard_mo" },
    isMainLine: false,
    tags: [],
    generation: 7,
    parentIds: ["christopher-coy"],
    spouseId: "frances-page",
    notes: null,
  },
  {
    id: "frances-page",
    name: "Frances Page",
    birth: { year: 1784, place: "virginia" },
    death: { year: 1852, place: "howard_mo" },
    isMainLine: false,
    tags: [],
    generation: 7,
    spouseId: "samuel-christopher-coy",
    notes: null,
  },
  {
    id: "jerusha-coy",
    name: "Jerusha Coy",
    birth: { year: 1780, place: "frederick_md" },
    death: { year: 1800, place: "madison_ky" },
    isMainLine: false,
    tags: [],
    generation: 7,
    parentIds: ["christopher-coy"],
    notes: null,
  },
  {
    id: "paulina-pierce-hamilton-coy",
    name: "Paulina Pierce Hamilton Coy",
    birth: { year: null, place: "bennington_vt" },
    death: { year: 1874, place: "waverly_ia" },
    isMainLine: false,
    tags: [],
    generation: 7,
    notes: null,
  },

  // ── Generation 8 ──────────────────────────────────────────
  {
    id: "phoebe-coy-1780",
    name: "Phoebe Coy",
    birth: { year: 1780, place: "madison_ky" },
    death: { year: 1815, place: "madison_ky" },
    isMainLine: false,
    tags: [],
    generation: 7,
    parentIds: ["christopher-coy"],
    notes: null,
  },
  {
    id: "stephen-coy",
    name: "Stephen Coy",
    birth: { year: 1790, place: "amherst_va" },
    death: { year: 1840, place: "clay_co_il" },
    isMainLine: true,
    tags: [],
    generation: 7,
    parentIds: ["christopher-coy"],
    spouseId: "mary-polly-million-adams",
    notes: "Born ~1790, Amherst County, Virginia — same county and era as Christopher Coy's documented daughter Elizabeth Neff (b.1792, Amherst VA), supporting the Christopher parentage. Parentage is strong circumstantially but no primary source yet confirms it; Christopher Coy's pension file W9798 (NARA M804) is the next step. Married Polly Million on July 27, 1817, Madison County, Kentucky (primary source: Madison County KY marriage index) — while his probable father Christopher was living in Madison County that same decade. Migrated from Madison County KY to Clay County IL sometime between 1827 and 1831 (children's birth places shift from KY to IL). Clay County formed December 23, 1824 — Stephen was a first-wave settler in newly organized territory. The 1840 federal census (Clay County, page 7, line 2) confirms him as head of household with 9 members — the last record of him alive. Died 1840, same year as the census. The family lived the flatboat economy: corn and hog surpluses floated down the Little Wabash River to the Ohio and Mississippi to New Orleans. Birth place corrected from clay_co_il (county didn't exist until 1824) to amherst_va per secondary genealogical databases.",
  },
  {
    id: "mary-polly-million-adams",
    name: "Mary Polly Million Adams",
    birth: { year: 1797, place: "virginia" },
    death: { year: 1849, place: "clay_co_il" },
    isMainLine: false,
    tags: [],
    generation: 8,
    spouseId: "stephen-coy",
    notes: "'Adams' is a middle name derived from a maternal family surname — a common Upper South naming convention — not a prior married name. No prior Adams marriage has been found. Married Stephen Coy on July 27, 1817, Madison County, Kentucky. Parents are very likely John Million Sr. (b.1763, Stafford County, VA; d.1850, Madison County, KY) and Lydia Butler — both married in Madison County KY in 1787. John Million Sr. filed a Revolutionary War pension in 1843; that file (NARA) would list his children by name and confirm Polly's parentage. Two 'Polly Million' women married in Madison County KY within four months in 1817 — one married Stephen Coy (Jul 27), one married Joel Sanders (Nov 16) — almost certainly sisters, both daughters of John Million Sr. The Million family was spreading into Illinois: John Sr.'s sister Sarah Ann (Million) Combs died in Edgar County, IL, the county directly north of Clay County. Polly outlived Stephen by nine years, dying 1849 in Clay County.",
  },
  {
    id: "john-coy-1783",
    name: "John Coy",
    birth: { year: 1783, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 7,
    parentIds: ["christopher-coy"],
    notes: "Birth year discrepancy: data.js has 1783, but pension file W9798 states he was 47 in 1840, implying b.~1793. A 10-year gap — one source is likely wrong. Appeared in pension file as a witness, living in 1840; stated he had 3 brothers and 3 sisters still living.",
  },
  {
    id: "nancy-coy-1792",
    name: "Nancy Coy",
    birth: { year: 1792, place: "frederick_md" },
    death: { year: 1892, place: "sullivan_mi" },
    isMainLine: false,
    tags: [],
    generation: 7,
    parentIds: ["christopher-coy"],
    spouseId: "john-cooper",
    notes: null,
  },
  {
    id: "john-cooper",
    name: "John Cooper",
    birth: { year: 1790, place: "virginia" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 8,
    spouseId: "nancy-coy-1792",
    notes: "Married 1817.",
  },
  {
    id: "daniel-coy-1793",
    name: "Daniel Coy",
    birth: { year: 1793, place: "maryland" },
    death: { year: 1865, place: "greene_park_in" },
    isMainLine: false,
    tags: [],
    generation: 7,
    parentIds: ["christopher-coy"],
    notes: null,
  },
  {
    id: "ephraim-coy-1798",
    name: "Ephraim Coy",
    birth: { year: 1798, place: "garrard_ky" },
    death: { year: 1870, place: "kansas" },
    isMainLine: false,
    tags: [],
    generation: 7,
    parentIds: ["christopher-coy"],
    spouseId: "peggy-green",
    notes: null,
  },
  {
    id: "peggy-green",
    name: "Peggy Green",
    birth: { year: 1800, place: "garrard_ky" },
    death: { year: 1850, place: "lawrence_il" },
    isMainLine: false,
    tags: [],
    generation: 8,
    spouseId: "ephraim-coy-1798",
    notes: null,
  },
  {
    id: "john-l-coy-1795",
    name: "John L. Coy",
    birth: { year: 1795, place: "paint_lick_ky" },
    death: { year: 1870, place: "prairie_mi" },
    isMainLine: false,
    tags: [],
    generation: 7,
    parentIds: ["christopher-coy"],
    spouseId: "sally-baker",
    notes: null,
  },
  {
    id: "sally-baker",
    name: "Sally Baker",
    birth: { year: 1795, place: "kentucky" },
    death: { year: 1848, place: null },
    isMainLine: false,
    tags: [],
    generation: 8,
    spouseId: "john-l-coy-1795",
    notes: null,
  },
  {
    id: "william-coy-1803",
    name: "William Coy",
    birth: { year: 1803, place: "kentucky" },
    death: { year: null, place: "switzerland_in" },
    isMainLine: false,
    tags: [],
    generation: 7,
    parentIds: ["christopher-coy"],
    spouseId: "sarah-chandler",
    notes: null,
  },
  {
    id: "sarah-chandler",
    name: "Sarah Chandler",
    birth: { year: 1800, place: "madison_ky" },
    death: { year: null, place: "madison_ky" },
    isMainLine: false,
    tags: [],
    generation: 8,
    spouseId: "william-coy-1803",
    notes: null,
  },
  {
    id: "samuel-coy-1803",
    name: "Samuel Coy",
    birth: { year: 1803, place: "kentucky" },
    death: { year: null, place: "indiana" },
    isMainLine: false,
    tags: [],
    generation: 7,
    parentIds: ["christopher-coy"],
    notes: null,
  },
  {
    id: "william-coy-1814",
    name: "William Coy",
    birth: { year: 1814, place: "clay_co_il" },
    death: { year: 1851, place: "coles_il" },
    isMainLine: true,
    tags: [],
    generation: 8,
    parentIds: ["stephen-coy"],
    spouseId: "dorcas-adams-radley",
    notes: null,
  },
  {
    id: "dorcas-adams-radley",
    name: "Dorcas Adams Radley",
    birth: { year: 1822, place: "hardin_ky" },
    death: { year: 1886, place: "decatur_il" },
    isMainLine: false,
    tags: [],
    generation: 8,
    parentIds: ["ichabod-b-radley", "hannah-bush-radley"],
    spouseId: "william-coy-1814",
    notes: "Daughter of Ichabod B. Radley and Hannah Bush Radley. Niece of Sarah Bush Lincoln — Abraham Lincoln's stepmother. Born December 1822, Hardin County, KY. GEDCOM also records a second marriage to Samuel Thomas (29 Mar 1858, Coles IL).",
  },
  {
    id: "thomas-coy-m1817",
    name: "Thomas Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 8,
    spouseId: "roseanna-warren",
    notes: "Married 1817.",
  },
  {
    id: "roseanna-warren",
    name: "Roseanna Warren",
    birth: { year: null, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 8,
    spouseId: "thomas-coy-m1817",
    notes: null,
  },
  {
    id: "anny-coy",
    name: "Anny Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 8,
    notes: "Married 1816.",
  },
  {
    id: "sally-coy-m1819",
    name: "Sally Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 8,
    spouseId: "samuel-pruett",
    notes: "Married 1819.",
  },
  {
    id: "samuel-pruett",
    name: "Samuel Pruett",
    birth: { year: null, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 8,
    spouseId: "sally-coy-m1819",
    notes: null,
  },
  {
    id: "polly-coy-m1827",
    name: "Polly Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 8,
    spouseId: "isaac-embry",
    notes: "Married 1827.",
  },
  {
    id: "isaac-embry",
    name: "Isaac Embry",
    birth: { year: null, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 8,
    spouseId: "polly-coy-m1827",
    notes: null,
  },

  // ── Generation 9 ──────────────────────────────────────────
  {
    id: "josephine-coy",
    name: "Josephine Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "james-cotton",
    notes: "Married 1865.",
  },
  {
    id: "james-cotton",
    name: "James Cotton",
    birth: { year: null, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "josephine-coy",
    notes: null,
  },
  {
    id: "irvine-coy",
    name: "Irvine Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "harriet-royston",
    notes: "Married 1869.",
  },
  {
    id: "harriet-royston",
    name: "Harriet Royston",
    birth: { year: null, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "irvine-coy",
    notes: null,
  },
  {
    id: "mary-l-coy",
    name: "Mary L. Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "roward-cotten",
    notes: "Married 1883.",
  },
  {
    id: "roward-cotten",
    name: "Roward Cotten",
    birth: { year: null, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "mary-l-coy",
    notes: null,
  },
  {
    id: "collins-coy",
    name: "Collins Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "nancy-f-long",
    notes: "Married 1878.",
  },
  {
    id: "nancy-f-long",
    name: "Nancy F. Long",
    birth: { year: null, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "collins-coy",
    notes: null,
  },
  {
    id: "alice-coy-m1889",
    name: "Alice Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "zack-simpson",
    notes: "Married 1889.",
  },
  {
    id: "zack-simpson",
    name: "Zack Simpson",
    birth: { year: null, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "alice-coy-m1889",
    notes: null,
  },
  {
    id: "william-n-coy",
    name: "William N. Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "alice-b-wheeler",
    notes: "Married 1886.",
  },
  {
    id: "alice-b-wheeler",
    name: "Alice B. Wheeler",
    birth: { year: null, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "william-n-coy",
    notes: null,
  },
  {
    id: "emma-coy",
    name: "Emma Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "smith-hagan",
    notes: "Married 1897.",
  },
  {
    id: "smith-hagan",
    name: "Smith Hagan",
    birth: { year: null, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "emma-coy",
    notes: null,
  },
  {
    id: "james-t-coy",
    name: "James T. Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "n-hattie-long",
    notes: "Married 1891.",
  },
  {
    id: "n-hattie-long",
    name: "N. Hattie Long",
    birth: { year: null, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "james-t-coy",
    notes: null,
  },
  {
    id: "cc-coy",
    name: "C. C. Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "pauline-roberts",
    notes: "Married 1894.",
  },
  {
    id: "pauline-roberts",
    name: "Pauline Roberts",
    birth: { year: null, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "cc-coy",
    notes: null,
  },
  {
    id: "ed-coy",
    name: "Ed Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "mattie-moran",
    notes: "Married 1898.",
  },
  {
    id: "mattie-moran",
    name: "Mattie Moran",
    birth: { year: null, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "ed-coy",
    notes: null,
  },
  {
    id: "myrtle-m-coy",
    name: "Myrtle M. Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "harry-clive-sharp",
    notes: "Married 1905.",
  },
  {
    id: "harry-clive-sharp",
    name: "Harry Clive Sharp",
    birth: { year: null, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "myrtle-m-coy",
    notes: null,
  },

  // ── Generation 9 (Illinois branch) ───────────────────────
  {
    id: "reuben-coy-1818",
    name: "Reuben Coy",
    birth: { year: 1818, place: "madison_ky" },
    death: { year: 1897, place: "cumberland_il" },
    isMainLine: false,
    tags: [],
    generation: 8,
    parentIds: ["stephen-coy"],
    notes: null,
  },
  {
    id: "mariah-coy-1823",
    name: "Mariah Coy",
    birth: { year: 1823, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 8,
    parentIds: ["stephen-coy"],
    notes: null,
  },
  {
    id: "permelia-coy",
    name: "Permelia Coy",
    birth: { year: 1823, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 8,
    parentIds: ["stephen-coy"],
    notes: null,
  },
  {
    id: "harrison-coy-1825",
    name: "Harrison Coy",
    birth: { year: 1825, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 8,
    parentIds: ["stephen-coy"],
    notes: null,
  },
  {
    id: "stephen-coy-1827",
    name: "Stephen Coy",
    birth: { year: 1827, place: "madison_ky" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 8,
    parentIds: ["stephen-coy"],
    notes: null,
  },
  {
    id: "margaret-jane-coy",
    name: "Margaret Jane Coy",
    birth: { year: 1831, place: "clay_co_il" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 8,
    parentIds: ["stephen-coy"],
    notes: null,
  },
  {
    id: "hannah-coy-1839",
    name: "Hannah Coy",
    birth: { year: 1839, place: "lawrence_il" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    parentIds: ["william-coy-1814"],
    notes: null,
  },
  {
    id: "nicholas-w-coy",
    name: "Nicholas W. Coy",
    birth: { year: 1842, place: "mattoon_il" },
    death: { year: 1912, place: "quincy_il" },
    isMainLine: true,
    tags: ["vet"],
    generation: 9,
    parentIds: ["william-coy-1814"],
    spouseId: "elizabeth-coy-rogers",
    notes: "Civil War veteran. In his later years lived in a shack on a river island in the bottoms near Decatur, IL — a local character known to the Macon County Sheriff's office. Local papers reported concern about him surviving winter outdoors. Eventually died at the Soldiers' Home in Quincy, IL; buried Quincy. Father of Nicholas W. Coy Jr.",
  },
  {
    id: "elizabeth-coy-rogers",
    name: "Elizabeth Coy Rogers",
    birth: { year: 1847, place: "moss_run_oh" },
    death: { year: 1921, place: "taylorville_il" },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "nicholas-w-coy",
    notes: null,
  },
  {
    id: "mary-j-coy-adams",
    name: "Mary J. Coy Adams",
    birth: { year: 1846, place: "cumberland_il" },
    death: { year: 1908, place: "hillsboro_il" },
    isMainLine: false,
    tags: [],
    generation: 9,
    parentIds: ["william-coy-1814"],
    notes: null,
  },
  {
    id: "stephen-a-coy-1847",
    name: "Stephen A. Coy",
    birth: { year: 1847, place: "cumberland_il" },
    death: { year: 1900, place: "effingham_il" },
    isMainLine: false,
    tags: [],
    generation: 9,
    parentIds: ["william-coy-1814"],
    notes: null,
  },
  {
    id: "hettie-ann-coy",
    name: "Hettie Ann Coy",
    birth: { year: 1849, place: "coles_il" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 9,
    parentIds: ["william-coy-1814"],
    notes: null,
  },

  // ── Generation 10 ─────────────────────────────────────────
  {
    id: "infant-death-shelby-1867a",
    name: "Infant Death",
    birth: { year: 1867, place: "shelby_co_il" },
    death: { year: 1867, place: "shelby_co_il" },
    isMainLine: false,
    tags: [],
    generation: 10,
    parentIds: ["nicholas-w-coy"],
    notes: null,
  },
  {
    id: "napolean-coy",
    name: "Napolean Coy",
    birth: { year: 1867, place: "shelby_co_il" },
    death: { year: 1867, place: "shelby_co_il" },
    isMainLine: false,
    tags: [],
    generation: 10,
    parentIds: ["nicholas-w-coy"],
    notes: null,
  },
  {
    id: "alice-coy-kinnicut",
    name: "Alice Coy Kinnicut",
    birth: { year: 1870, place: "shelby_co_il" },
    death: { year: 1954, place: "sangamon_il" },
    isMainLine: false,
    tags: [],
    generation: 10,
    parentIds: ["nicholas-w-coy"],
    notes: null,
  },
  {
    id: "amanda-guy-boyd",
    name: "Amanda Guy Boyd",
    birth: { year: 1875, place: "hillsboro_il" },
    death: { year: 1959, place: "east_peoria_il" },
    isMainLine: false,
    tags: [],
    generation: 10,
    parentIds: ["nicholas-w-coy"],
    notes: null,
  },
  {
    id: "nicholas-w-coy-jr",
    name: "Nicholas W. Coy Jr.",
    birth: { year: 1877, place: "mt_zion_il" },
    death: { year: 1955, place: "lewiston_id" },
    isMainLine: true,
    tags: [],
    generation: 10,
    parentIds: ["nicholas-w-coy"],
    spouseId: "lydia-ellen-mackey",
    notes: "Lived with family at 1522 North Gulick Ave, Decatur, IL. Had at least 7 children: Carl, Robert, Roy, Ernest, Walter, Earl Edwin (died age 2, diphtheria), and Donald R. Coy (main line, Gen 11). Son Ernest was killed in a scaffold accident in Decatur in 1929. Eventually moved to Lewiston, ID with the main family migration.",
  },
  {
    id: "lydia-ellen-mackey",
    name: "Lydia Ellen Mackey",
    birth: { year: 1882, place: "mt_zion_il" },
    death: { year: 1940, place: "winchester_id" },
    isMainLine: false,
    tags: [],
    generation: 10,
    parentIds: ["peter-mackey", "armina-mackey-rowe"],
    spouseId: "nicholas-w-coy-jr",
    notes: null,
  },
  {
    id: "stephen-elmer-coy",
    name: "Stephen Elmer Coy",
    birth: { year: 1879, place: "mattoon_il" },
    death: { year: 1928, place: "kincaid_il" },
    isMainLine: false,
    tags: [],
    generation: 10,
    parentIds: ["nicholas-w-coy"],
    notes: null,
  },
  {
    id: "nettie-coy-thomas",
    name: "Nettie Coy",
    birth: { year: null, place: "coles_il" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 10,
    parentIds: ["nicholas-w-coy"],
    spouseId: "george-thomas-1890",
    notes: "Probable daughter of Nicholas W. Coy and Elizabeth Rogers. Married George Thomas on April 12, 1890, Coles County, IL (Coles County marriage records). Birth year unconfirmed.",
  },
  {
    id: "george-thomas-1890",
    name: "George Thomas",
    birth: { year: null, place: "coles_il" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 10,
    spouseId: "nettie-coy-thomas",
    notes: "Married Nettie Coy, April 12, 1890, Coles County, IL.",
  },

  // ── Generation 11 ─────────────────────────────────────────
  {
    id: "infant-death-neoga-1888",
    name: "Infant Death",
    birth: { year: 1888, place: "neoga_il" },
    death: { year: 1888, place: "neoga_il" },
    isMainLine: false,
    tags: [],
    generation: 10,
    parentIds: ["nicholas-w-coy"],
    notes: null,
  },
  {
    id: "donald-r-coy",
    name: "Donald R. Coy",
    birth: { year: 1916, place: "decatur_il" },
    death: { year: 1957, place: "lewiston_id" },
    isMainLine: true,
    tags: [],
    generation: 11,
    parentIds: ["nicholas-w-coy-jr"],
    spouseId: "ruth-coy-woolridge",
    notes: "Died at 41 — same early death pattern as his grandfather William (d.37). Had 5 children: Ernest Dale, Francis 'Bill' William, Jo Ann (Reed), Ruby (Sandahl), and Lizzy Lou. Family arrived in Idaho ~1937–38; Ernest Dale was born in Lovington, IL in April 1937, and Dixie Lea Bruun (Ernest's future wife) was born in Winchester, ID in 1938.",
  },
  {
    id: "ruth-coy-woolridge",
    name: "Ruth Coy Woolridge",
    birth: { year: 1916, place: "macon_il" },
    death: { year: 2011, place: "lewiston_id" },
    isMainLine: false,
    tags: [],
    generation: 11,
    parentIds: ["john-william-woolridge", "lizzie-woolridge"],
    spouseId: "donald-r-coy",
    notes: "Died April 12, 2011 in Lewiston at age ~94–95. Outlived Donald by 54 years. Obituary: 'Ruth Coy, 94, Lewiston' in Lewiston Morning Tribune. Her father John William Woolridge was born 1888 in Hays, Ellis County, Kansas.",
  },

  // ── Generation 11 (siblings of Donald R. Coy — children of Nicholas Jr.) ──
  {
    id: "earl-edwin-coy",
    name: "Earl Edwin Coy",
    birth: { year: null, place: "decatur_il" },
    death: { year: null, place: "decatur_il" },
    isMainLine: false,
    tags: [],
    generation: 11,
    parentIds: ["nicholas-w-coy-jr"],
    notes: "Son of Nicholas W. Coy Jr. and Lydia Ellen Mackey. Died at age 2 from diphtheria at the family home at 1522 North Gulick Ave, Decatur, IL. No public funeral due to contagion; buried at Greenwood Cemetery, Decatur.",
  },
  {
    id: "carl-coy",
    name: "Carl Mackey Coy",
    birth: { year: 1900, place: "decatur_il" },
    death: { year: 1946, place: "winchester_id" },
    isMainLine: false,
    tags: [],
    generation: 11,
    parentIds: ["nicholas-w-coy-jr"],
    notes: "Son of Nicholas W. Coy Jr. Full name Carl Mackey Coy. Listed as surviving sibling in Earl Edwin Coy obituary, Decatur, IL.",
  },
  {
    id: "robert-coy-1900s",
    name: "Robert N. Coy",
    birth: { year: null, place: "decatur_il" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 11,
    parentIds: ["nicholas-w-coy-jr"],
    notes: "Son of Nicholas W. Coy Jr. Listed as surviving sibling in Earl Edwin Coy obituary, Decatur, IL.",
  },
  {
    id: "roy-coy",
    name: "Roy E. Coy",
    birth: { year: null, place: "decatur_il" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 11,
    parentIds: ["nicholas-w-coy-jr"],
    notes: "Son of Nicholas W. Coy Jr. Listed as surviving sibling in Earl Edwin Coy obituary, Decatur, IL.",
  },
  {
    id: "ernest-coy-1929",
    name: "Earnest G. Coy",
    birth: { year: null, place: "decatur_il" },
    death: { year: 1929, place: "decatur_il" },
    isMainLine: false,
    tags: [],
    generation: 11,
    parentIds: ["nicholas-w-coy-jr"],
    notes: "Son of Nicholas W. Coy Jr. Killed October 1929 when a scaffold collapsed at the Shellabarger Soy Bean Mill in Decatur, IL — fell 80 feet into a grain bin. Lived at West Eldorado Drive, Pines addition, Decatur. Source: Decatur Herald, October 8, 1929.",
  },
  {
    id: "walter-coy",
    name: "Walter Otto Coy",
    birth: { year: 1912, place: "decatur_il" },
    death: { year: 1975, place: "clarkston_wa" },
    isMainLine: false,
    tags: [],
    generation: 11,
    parentIds: ["nicholas-w-coy-jr"],
    notes: "Son of Nicholas W. Coy Jr. Full name Walter Otto Coy. Died in Clarkston, Asotin County, WA.",
  },

  // ── Bush-Radley branch (Dorcas Adams Radley's family) ────────────────────
  // Christopher Bush + Hannah Davis → Hannah Bush Radley (& Sarah Bush Lincoln)
  // Hannah Bush Radley + Ichabod B. Radley → Dorcas Adams Radley
  {
    id: "christopher-bush",
    name: "Christopher Bush",
    birth: { year: 1735, place: "rotterdam" },
    death: { year: 1813, place: "hardin_ky" },
    isMainLine: false,
    tags: [],
    generation: 6,
    spouseId: "hannah-davis-bush",
    notes: "Father of Hannah Bush Radley and Sarah Bush Lincoln. Sarah Bush Lincoln became Abraham Lincoln's stepmother when she married Thomas Lincoln in 1819. GEDCOM records his birthplace as Rotterdam, Zuid-Holland, Netherlands (2 Jun 1735). Died in Elizabethtown, Hardin County, KY.",
  },
  {
    id: "hannah-davis-bush",
    name: "Hannah Davis",
    birth: { year: 1750, place: "virginia" },
    death: { year: 1835, place: "hardin_ky" },
    isMainLine: false,
    tags: [],
    generation: 6,
    spouseId: "christopher-bush",
    notes: "Died in Elizabethtown, Hardin County, KY.",
  },
  {
    id: "ichabod-b-radley",
    name: "Ichabod B. Radley",
    birth: { year: 1774, place: "elizabeth_nj" },
    death: { year: 1847, place: "coles_il" },
    isMainLine: false,
    tags: [],
    generation: 7,
    spouseId: "hannah-bush-radley",
    notes: "Born in Elizabeth, Essex (now Union) County, NJ. Died in Coles County, IL.",
  },
  {
    id: "hannah-bush-radley",
    name: "Hannah Bush Radley",
    birth: { year: 1777, place: "virginia" },
    death: { year: 1856, place: "coles_il" },
    isMainLine: false,
    tags: [],
    generation: 7,
    parentIds: ["christopher-bush", "hannah-davis-bush"],
    spouseId: "ichabod-b-radley",
    notes: "Daughter of Christopher Bush and Hannah Davis. Sister of Sarah Bush Lincoln, Abraham Lincoln's stepmother. Died in Coles County, IL.",
  },
  {
    id: "sarah-bush-lincoln",
    name: "Sarah Bush Lincoln",
    birth: { year: 1788, place: "hardin_ky" },
    death: { year: 1869, place: "coles_il" },
    isMainLine: false,
    tags: [],
    generation: 7,
    parentIds: ["christopher-bush", "hannah-davis-bush"],
    notes: "Abraham Lincoln's stepmother. Married Daniel Johnston first (three children), then Thomas Lincoln in 1819 after both were widowed. Raised Lincoln alongside her own children; Lincoln credited her as a major influence on his life. Died in Janesville, Coles County, IL.",
  },

  // ── Mackey branch (parents of Lydia Ellen Mackey) ────────
  {
    id: "peter-mackey",
    name: "Peter Mackey",
    birth: { year: 1849, place: "franklin_pa" },
    death: { year: 1915, place: "decatur_il" },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "armina-mackey-rowe",
    notes: "Father of Lydia Ellen Mackey. Born 25 Jul 1849, Franklin Co., Pennsylvania. Died 21 Feb 1915, Decatur, Macon Co., Illinois.",
  },
  {
    id: "armina-mackey-rowe",
    name: "Armina Mackey Rowe",
    birth: { year: 1854, place: "macoupin_il" },
    death: { year: 1935, place: "moultrie_il" },
    isMainLine: false,
    tags: [],
    generation: 9,
    spouseId: "peter-mackey",
    notes: "Mother of Lydia Ellen Mackey. Born 5 Sep 1854, American Bottoms, Macoupin Co., Illinois. Died 7 Dec 1935, Lovington, Moultrie Co., Illinois.",
  },

  // ── Woolridge branch (parents of Ruth Coy Woolridge) ─────
  {
    id: "john-william-woolridge",
    name: "John William Woolridge",
    birth: { year: 1888, place: "ellis_ks" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 10,
    spouseId: "lizzie-woolridge",
    notes: "Father of Ruth Coy Woolridge. Born 16 December 1888, Hays, Ellis County, Kansas.",
  },
  {
    id: "lizzie-woolridge",
    name: "Lizzie Woolridge",
    birth: { year: null, place: "illinois" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 10,
    spouseId: "john-william-woolridge",
    notes: "Mother of Ruth Coy Woolridge. Born in Illinois.",
  },

  // ── Bruun branch (parents of Dixie Lee Coy Bruun) ────────
  {
    id: "george-bruun",
    name: "George Bruun",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 11,
    spouseId: "wilma-blanch-howard",
    notes: "Father of Dixie Lee Coy Bruun.",
  },
  {
    id: "wilma-blanch-howard",
    name: "Wilma Blanch Howard",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 11,
    spouseId: "george-bruun",
    notes: "Mother of Dixie Lee Coy Bruun.",
  },

  // ── Generation 11 (remaining children of Donald R. Coy) ──────────────────
  {
    id: "francis-bill-coy",
    name: 'Francis "Bill" William Coy',
    birth: { year: null, place: "lewiston_id" },
    death: { year: 2019, place: "lewiston_id" },
    isMainLine: false,
    tags: [],
    generation: 11,
    parentIds: ["donald-r-coy"],
    spouseId: "sherry-coy",
    notes: "Son of Donald and Ruth Coy. Married Sherry for 36 years. Journeyman papermaker, then paper machine boss (tissue side) at Potlatch Corp. for 38½ years — identical career length to his brother Ernest Dale. Volunteer fireman in the Lewiston Orchards for years. Predeceased by daughter Terry and by brother Ernie (2013). Survived by son Scott (Sara) Coy; grandchildren Khea Sherman, Kelsey (Andrew) Castaneda, Kolby Coy. Source: Lewiston Morning Tribune, July 16, 2019.",
  },
  {
    id: "sherry-coy",
    name: "Sherry Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 11,
    spouseId: "francis-bill-coy",
    notes: "Wife of Francis 'Bill' William Coy; married 36 years. Maiden name unknown.",
  },
  {
    id: "joann-coy-reed",
    name: "Jo Ann (Coy) Reed",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 11,
    parentIds: ["donald-r-coy"],
    notes: "Daughter of Donald and Ruth Coy. Married name Reed. Listed as surviving sister in both Ernest Dale (2013) and Francis 'Bill' William (2019) Coy obituaries.",
  },
  {
    id: "ruby-coy-sandahl",
    name: "Ruby (Coy) Sandahl",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 11,
    parentIds: ["donald-r-coy"],
    notes: "Daughter of Donald and Ruth Coy. Married name Sandahl. Mother of Dr. Barbara L. Givens MD (b. May 4, 1958, Lewiston ID; d. Jan 26, 2018, Pacific Beach WA) — University of Washington MD, Internal Medicine, practiced at Grays Harbor Community Hospital, Aberdeen WA. Barbara's father listed as Larry E. Lefler Sr.",
  },
  {
    id: "lizzy-lou-coy",
    name: "Lizzy Lou Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 11,
    parentIds: ["donald-r-coy"],
    notes: "Daughter of Donald and Ruth Coy. Listed as surviving sister in both Ernest Dale (2013) and Francis 'Bill' William (2019) Coy obituaries. Birth/death dates unconfirmed.",
  },

  // ── Generation 12 ─────────────────────────────────────────
  {
    id: "ernest-dale-coy",
    name: 'Ernest "Ernie" Dale Coy Sr.',
    birth: { year: 1937, place: "moultrie_il" },
    death: { year: 2013, place: "lewiston_id" },
    isMainLine: true,
    tags: [],
    generation: 12,
    parentIds: ["donald-r-coy"],
    spouseId: "dixie-lee-coy-bruun",
    notes: "Born April 9, 1937, Lovington, Moultrie County, IL. Died November 7, 2013, St. Joseph Regional Medical Center, Lewiston. Married Dixie Lea Bruun December 2, 1955, Lewiston — married 58 years. Journeyman electrician at Potlatch Corp. for 38½ years. Six children; predeceased by son Richard Dennis Coy. 19 grandchildren, 12 great-grandchildren. Source: Lewiston Morning Tribune obituary.",
  },
  {
    id: "dixie-lee-coy-bruun",
    name: "Dixie Lea Bruun",
    birth: { year: 1938, place: "winchester_id" },
    death: { year: null, place: "lewiston_id" },
    isMainLine: false,
    tags: [],
    generation: 12,
    parentIds: ["george-bruun", "wilma-blanch-howard"],
    spouseId: "ernest-dale-coy",
    notes: "Born Winchester, ID, 1938. A native Idahoan — born the year the Coy family arrived. Married Ernest Dale Coy Sr. December 2, 1955, Lewiston. Still living in Lewiston per 2013 obituary.",
  },

  // ── Generation 13 (children of Ernest Dale Coy Sr.) ───────
  {
    id: "ernest-dale-coy-jr",
    name: "Ernest Dale Coy Jr.",
    birth: { year: null, place: "lewiston_id" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 13,
    parentIds: ["ernest-dale-coy"],
    spouseId: "vivian-coy",
    notes: null,
  },
  {
    id: "vivian-coy",
    name: "Vivian Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 13,
    spouseId: "ernest-dale-coy-jr",
    notes: null,
  },
  {
    id: "dixie-kay-smith",
    name: "Dixie Kay (Coy) Smith",
    birth: { year: null, place: "lewiston_id" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 13,
    parentIds: ["ernest-dale-coy"],
    spouseId: "mark-smith-lewiston",
    notes: null,
  },
  {
    id: "mark-smith-lewiston",
    name: "Mark Smith",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 13,
    spouseId: "dixie-kay-smith",
    notes: null,
  },
  {
    id: "dan-tiger-coy",
    name: 'Dan "Tiger" Edward Coy',
    birth: { year: null, place: "lewiston_id" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 13,
    parentIds: ["ernest-dale-coy"],
    spouseId: "christine-coy",
    notes: null,
  },
  {
    id: "christine-coy",
    name: "Christine Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 13,
    spouseId: "dan-tiger-coy",
    notes: null,
  },
  {
    id: "john-william-coy-lewiston",
    name: "John William Coy",
    birth: { year: null, place: "lewiston_id" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 13,
    parentIds: ["ernest-dale-coy"],
    spouseId: "asia-coy",
    notes: null,
  },
  {
    id: "asia-coy",
    name: "Asia Coy",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 13,
    spouseId: "john-william-coy-lewiston",
    notes: null,
  },
  {
    id: "emily-jean-holzer",
    name: "Emily Jean (Coy) Holzer",
    birth: { year: null, place: "lewiston_id" },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 13,
    parentIds: ["ernest-dale-coy"],
    spouseId: "rick-holzer",
    notes: null,
  },
  {
    id: "rick-holzer",
    name: "Rick Holzer",
    birth: { year: null, place: null },
    death: { year: null, place: null },
    isMainLine: false,
    tags: [],
    generation: 13,
    spouseId: "emily-jean-holzer",
    notes: null,
  },
  {
    id: "richard-dennis-coy",
    name: "Richard Dennis Coy",
    birth: { year: null, place: "lewiston_id" },
    death: { year: null, place: "lewiston_id" },
    isMainLine: false,
    tags: [],
    generation: 13,
    parentIds: ["ernest-dale-coy"],
    notes: "Predeceased his father Ernest Dale Coy Sr. Listed in 2013 obituary as preceded in death.",
  },
]
